### ISSUE TITLE
kernel.py

### ISSUE THREAD

**Issue by KhangDeveloperd** [Alter-Net-codes/SkyOS#4]
kernel.py is fked again. (sorry if Im swearing)

**Comment by webbrowser11** [comment]
let me try...

**Comment by webbrowser11** [comment]
i do not like the things microboy added exepr

**Comment by webbrowser11** [comment]
*i do not like the things micro boy added expect the kernel panic

**Comment by webbrowser11** [comment]
@KhangDeveloperd is 2.4 working?

**Comment by MicroboyLLC** [comment]
🤦 If you don't like it, then at least not have your code be buggy, or just transfer it to me so I can rewrite your code in Java for use on one of those Java CPUs that run Java bytecode as a .class file? I have fixed SO MUCH and cleaned up your buggy and untidy code, and you don't like the literal improvements? Why the [censored] did you remove the Java support, anyway? Is it because you thought it was "buggy"? I know a lot of Python, but I honestly wonder your Python knowledge level, but then again, even I have my limits, and I don't want to be an example of the Dunning-Kreuger effect for being overconfident, but you're the one who originally used LITERAL C CODE to shut down the computer.

**Comment by webbrowser11** [comment]
look @KhangDeveloperd i know its f'ed up rn if i find out how to fix it  YAY!!! or if microboy figures out how to fix it while writing java edition then we can fix it and release the fully bugfixed version

**Comment by webbrowser11** [comment]
@KhangDeveloperd  fixed!!! download 2.4.2! (yes the whole thing works) OMG finally!!!!

**Comment by KhangDeveloperd** [comment]
woah it works 🥶🥶🥶

**Comment by webbrowser11** [comment]
wtf with the emojis

**Comment by webbrowser11** [comment]
also yes it know works and the devs can take a week or two break u think that Microsoft is always updating windows?

**Comment by KhangDeveloperd** [comment]
yeah

**Comment by webbrowser11** [comment]
XD i just fixed one more thing in the bios it works fully now.
