### ISSUE TITLE
i wanna contribute

### ISSUE THREAD

**Issue by Alejandrix2456github** [Alter-Net-codes/SkyOS#8]
i will make the Browser App, Files App and more stuff

**Comment by webbrowser11** [comment]
okay, we do need a file manager and a browser but... IT HAS TO BE:
PYTHON!!!!!!!!! because we aim to create a 100% python OS. so before i let you into the repo do you want to be an Alter Net employee?

**Comment by webbrowser11** [comment]
also ale,

**Comment by webbrowser11** [comment]
we have to release SkyOS 2.6 so before we give you full access we will have to have you fork this repo and once your version is fully bug fixed merge it. please only create and commit to the apps you make we will do the rest once merged. best wishes on building 2.7! -webbrowser11 (JUST MAKING SURE IT IS CLEAR only fork the repo once i come to this issue and tell you to)

**Comment by webbrowser11** [comment]
@Alejandrix2456github
u there?

**Comment by webbrowser11** [comment]
ALE?

**Comment by Alejandrix2456github** [comment]
I was in scratch duh

**Comment by webbrowser11** [comment]
k

**Comment by webbrowser11** [comment]
just follow the instructions i gave you.

**Comment by webbrowser11** [comment]
anyways do consider working harder unless u want to be added in the last update in 2 yearsXD

**Comment by webbrowser11** [comment]
@malwarepad said it was not possible yet here we are making it, testing it, and running it and then, releasing it. i just want to see if other people making C operating systems would believe it.

**Comment by malwarepad** [comment]
> @malwarepad said it was not possible yet here we are making it, testing it, and running it and then, releasing it. i just want to see if other people making C operating systems would believe it.

When I saw the issue pop up on my repository, I thought you were a serious kernel developer. I apologize for my oversight; you clearly don't know what you're talking about.

An operating system's kernel is something intended to run directly on bare metal and interface with real hardware components, primarily a CPU, memory, etc. 

The thing you're making right now is just a userspace interpreted python script that runs on top of existing OSes. This is by no means an operating system, not even a shell (as it runs under python). I appreciate the enthusiasm but dropping my name like that is not appreciated. I (along with actual kernel developers) don't "believe it" because it's not real.

Replying here feels like a real doctor stepping in on children playing acting games, but you are not children. Act accordingly.

**Comment by webbrowser11** [comment]
> I was in scratch duh

bro ale, u there?

**Comment by webbrowser11** [comment]
k bye idk
